# Site Settings
title: frian@github
email: a@frian.org
baseurl: ""
url: "http://localhost:4000"
# Build Settings
sass:
  sass_dir: _sass
  load_paths:
     - "/usr/share/compass/frameworks/compass/stylesheets"
include: ['_pages']
kramdown:
  input: GFM
